// vue/src/components/game/GameBoard.vue
<script lang="ts" setup>
import { ref, defineProps, defineEmits } from 'vue';
import { CellMatrix, initializeCellMatrix, getNextCellMatrixState, Coordinates, CellState } from 'game-of-life-core';
import CellMatrixField from '../cells/CellMatrixField.vue';
import GameBoardMenu from './GameBoardMenu.vue';
import TimedCounter from '../core/TimedCounter.vue';

const props = defineProps<{ rows: number, columns: number, infiniteGameBoard: boolean }>();

const gameRunning = ref(false);

const emit = defineEmits(['back']);

const emitBack = () => {
  emit('back', null);
};

const cellMatrix = ref<CellMatrix>(initializeCellMatrix(props.rows, props.columns));

const handleCellClick = (coordinates: Coordinates) => {
  const { xAxis, yAxis } = coordinates;
  const nextState: CellState = cellMatrix.value[xAxis][yAxis].state === 'alive' ? 'dead' : 'alive';

  const updatedCellMatrix: CellMatrix = [...cellMatrix.value];
  updatedCellMatrix[xAxis][yAxis].state = nextState;

  cellMatrix.value = updatedCellMatrix;
};

const handleRunGame = () => {
  gameRunning.value = !gameRunning.value;
};

const handleResetState = () => {
  cellMatrix.value = initializeCellMatrix(props.rows, props.columns);
  gameRunning.value = false;
};

const handleGetNextState = () => {
  cellMatrix.value = getNextCellMatrixState(cellMatrix.value, props.infiniteGameBoard);
};
</script>

<template>
  <div className="w-full h-screen py-2 xl:w-2/3 flex flex-col justify-center">
    <div className="flex justify-center">
      <h1 className="font-bold text-2xl py-3 text-blue-600">Game of Life</h1>
    </div>
    <CellMatrixField :cellMatrix="cellMatrix" @cellClick="handleCellClick" />
    <GameBoardMenu @run="handleRunGame" @reset="handleResetState" @next="handleGetNextState" />
  </div>
  <TimedCounter v-if="gameRunning" :interval="100" @count="handleGetNextState" />
</template>

// src/components/game/GameBoard.tsx
import { useState } from 'react';
import { CellMatrix, CellState, Coordinates } from '../../types/game';
import { initializeCellMatrix } from '../../functions/game';
import { getNextCellMatrixState } from '../../functions/rules';
import TimedCounter from '../core/TimedCounter';
import CellMatrixField from '../cells/CellMatrixField';
import ZoomableWindow from '../core/ZoomableWindow';
import GameBoardMenu from './GameBoardMenu';
import { CallBack } from '../../types/callbacks';

const GameBoard = ({ rows, columns, infiniteGameBoard, onBack }: { rows: number, columns: number, infiniteGameBoard: boolean, onBack: CallBack }) => {
    const [cellMatrix, setCellMatrix] = useState<CellMatrix>(initializeCellMatrix(rows, columns));
    const [gameRunning, setGameRunning] = useState<boolean>(false);

    const handleCellClick = (coordinates: Coordinates) => {
        const { xAxis, yAxis } = coordinates;
        const nextState: CellState = cellMatrix[xAxis][yAxis].state === 'alive' ? 'dead' : 'alive';

        const updatedCellMatrix: CellMatrix = [...cellMatrix];
        updatedCellMatrix[xAxis][yAxis].state = nextState;

        setCellMatrix(updatedCellMatrix);
    };

    const handleRunGame = () => {
        setGameRunning((current) => !current);
    };

    const handleResetState = () => {
        setCellMatrix(initializeCellMatrix(rows, columns));
        setGameRunning(false);
    };

    const handleGetNextState = () => {
        setCellMatrix((current) => getNextCellMatrixState(current, infiniteGameBoard));
    };

    const handleRandomizeState = () => {
        setCellMatrix(initializeCellMatrix(rows, columns, true));
    };

    return <div className="w-full h-full xl:w-2/3 flex flex-col justify-center">
        <div className="flex justify-center">
            <h1 className="font-bold text-2xl py-3 text-blue-600">Game of Life</h1>
        </div>
        <ZoomableWindow zoomEnabled={!gameRunning}>
            <CellMatrixField cellMatrix={cellMatrix} onCellClick={handleCellClick} />
        </ZoomableWindow>
        <GameBoardMenu
            gameRunning={gameRunning}
            onRun={handleRunGame}
            onReset={handleResetState}
            onNext={handleGetNextState}
            onRandomize={handleRandomizeState} 
            onBack={onBack}
            />
        {gameRunning && <TimedCounter interval={100} onCount={handleGetNextState} />}
    </div >;
};

export default GameBoard;
