// vue/src/components/cells/CellMatrixField.vue
<script lang="ts" setup>
import { defineProps, defineEmits } from 'vue';
import CellSquare from './CellSquare.vue';
import { CellMatrix, Coordinates } from 'game-of-life-core';

const props = defineProps<{ cellMatrix: CellMatrix }>();

const emit = defineEmits(['cellClick']);

const emitCellClick = (coordinates: Coordinates) => {
  emit('cellClick', coordinates);
};
</script>

<template>
    <div class="border-2 border-black">
        <div class="flex justify-center" v-for="(cellRow, xAxis) in props.cellMatrix" :key="'row-' + xAxis">
            <CellSquare v-for="(cell, yAxis) in cellRow" :key="'cell-' + yAxis" :cell="cell" @click="emitCellClick({ xAxis: xAxis, yAxis: yAxis })" />
        </div>
    </div>
</template>

// src/components/CellMatrixField.tsx
import { CoordinatesCallBack } from '../types/callbacks';
import { Cell, CellMatrix } from '../types/game';
import CellSquare from './CellSquare';

const CellMatrixField = ({ cellMatrix, onCellClick }: { cellMatrix: CellMatrix, onCellClick: CoordinatesCallBack }) => {
	return <div className="border-2 border-black">
		{
			cellMatrix.map((cellRow: Cell[], xAxis: number) => <div key={'row-' + xAxis} className="flex justify-center">
				{
					cellRow.map((cell: Cell, yAxis: number) => {
						return <CellSquare
							key={'cell-' + xAxis + yAxis}
							cell={cell}
							onClick={() => onCellClick({ xAxis: xAxis, yAxis: yAxis })} />;
					})
				}
			</div>)
		}
	</div>;
};

export default CellMatrixField;
