// src/components/GameBoard.tsx
import { useState } from "react";
import { CellMatrix, CellState, Coordinates } from "../types/game";
import { initializeCellMatrix } from "../core/game";
import { getNextCellMatrixState } from "../core/rules";
import TimedCounter from "./TimedCounter";
import CellMatrixField from "./CellMatrixField";
import Button from "./Button";
import ZoomableWindow from "./ZoomableWindow";

const GameBoard = ({ rows, columns }: { rows: number, columns: number }) => {
    const [cellMatrix, setCellMatrix] = useState<CellMatrix>(initializeCellMatrix(rows, columns));
    const [gameRunning, setGameRunning] = useState<boolean>(false);

    const handleCellClick = (coordinates: Coordinates) => {
        const { xAxis, yAxis } = coordinates;
        const nextState: CellState = cellMatrix[xAxis][yAxis].state === 'alive' ? 'dead' : 'alive';

        const updatedCellMatrix: CellMatrix = [...cellMatrix];
        updatedCellMatrix[xAxis][yAxis].state = nextState;

        setCellMatrix(updatedCellMatrix);
    };

    const handleGetNextState = () => {
        setCellMatrix((current) => getNextCellMatrixState(current));
    };

    const handleResetState = () => {
        setCellMatrix(initializeCellMatrix(rows, columns));
        setGameRunning(false);
    };

    const handleRunGame = () => {
        setGameRunning((current) => !current);
    };

    return <div className="w-full h-full xl:w-2/3 flex flex-col justify-center pt-5">
        <ZoomableWindow>
            <CellMatrixField cellMatrix={cellMatrix} onCellClick={handleCellClick} />
        </ZoomableWindow>
        <div className="py-3 w-full flex justify-between">
            <div className="pe-1 w-full">
                {
                    !gameRunning ?

                        <Button text="Run game" color="green" onClick={handleRunGame} />
                        :
                        <Button text="Stop game" color="red" onClick={handleRunGame} />
                }
            </div>
            <div className="px-1 w-full">
                <Button text="Reset" color="gray" onClick={handleResetState} />
            </div>
            <div className="ps-1 w-full">
                <Button text="Get next state" color="blue" onClick={handleGetNextState} />
            </div>
        </div>
        {gameRunning && <TimedCounter interval={10} onCount={handleGetNextState} />}
    </div>;
};

export default GameBoard;

// vue/src/components/game/GameBoard.vue
<script lang="ts" setup>
import { ref, defineProps, defineEmits } from 'vue';
import { CellMatrix, initializeCellMatrix, getNextCellMatrixState, Coordinates, CellState } from 'game-of-life-core';
import CellMatrixField from '../cells/CellMatrixField.vue';
import GameBoardMenu from './GameBoardMenu.vue';
import TimedCounter from '../core/TimedCounter.vue';

const props = defineProps<{ rows: number, columns: number, infiniteGameBoard: boolean }>();

const gameRunning = ref(false);

const emit = defineEmits(['back']);

const emitBack = () => {
  emit('back', null);
};

const cellMatrix = ref<CellMatrix>(initializeCellMatrix(props.rows, props.columns));

const handleCellClick = (coordinates: Coordinates) => {
  const { xAxis, yAxis } = coordinates;
  const nextState: CellState = cellMatrix.value[xAxis][yAxis].state === 'alive' ? 'dead' : 'alive';

  const updatedCellMatrix: CellMatrix = [...cellMatrix.value];
  updatedCellMatrix[xAxis][yAxis].state = nextState;

  cellMatrix.value = updatedCellMatrix;
};

const handleRunGame = () => {
  gameRunning.value = !gameRunning.value;
};

const handleResetState = () => {
  cellMatrix.value = initializeCellMatrix(props.rows, props.columns);
  gameRunning.value = false;
};

const handleGetNextState = () => {
  cellMatrix.value = getNextCellMatrixState(cellMatrix.value, props.infiniteGameBoard);
};
</script>

<template>
  <div className="w-full h-screen py-2 xl:w-2/3 flex flex-col justify-center">
    <div className="flex justify-center">
      <h1 className="font-bold text-2xl py-3 text-blue-600">Game of Life</h1>
    </div>
    <CellMatrixField :cellMatrix="cellMatrix" @cellClick="handleCellClick" />
    <GameBoardMenu @run="handleRunGame" @reset="handleResetState" @next="handleGetNextState" />
  </div>
  <TimedCounter v-if="gameRunning" :interval="100" @count="handleGetNextState" />
</template>
