// src/components/game/MainMenu.tsx
import { useState } from 'react';
import GameLogo from '../core/GameLogo';
import Button from '../core/Button';
import GameBoard from './GameBoard';
import NumberInput from '../core/NumberInput';
import { GameBoardSize } from '../../types/game';
import CheckBoxInput from '../core/CheckBoxInput';

const MainMenu = () => {
    const [startGame, setStartGame] = useState<boolean>(false);
    const [gameBoardSize, setGameBoardSize] = useState<GameBoardSize>(getDefaultGameBoardSize());
    const [infiniteGameBoard, setInfiniteGameBoard] = useState<boolean>(false);

    function getDefaultGameBoardSize(): GameBoardSize {
        if (window.innerWidth <= 640) {
            return { rows: 40, columns: 25 };
        }

        if (window.innerWidth <= 768) {
            return { rows: 40, columns: 50 };
        }

        return { rows: 40, columns: 70 };
    }

    if (startGame) {
        return <GameBoard
            rows={gameBoardSize.rows}
            columns={gameBoardSize.columns}
            infiniteGameBoard={infiniteGameBoard} onBack={() => setStartGame(false)}
        />;
    }

    const handleStartGame = () => {
        if (gameBoardSize.rows > 0 && gameBoardSize.columns > 0) {
            setStartGame(true);
        }
    };

    const handleGameBoardSizeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const newValue: number | string = event.target.value ? parseInt(event.target.value) : '';
        setGameBoardSize({ ...gameBoardSize, [event.target.name]: newValue });
    };

    return <div className="w-full h-2/3 lg:w-1/2 rounded-md flex flex-col justify-center items-center bg-white shadow-sm border border-black">
        <h1 className="font-bold text-2xl py-3 text-blue-600">Game of Life</h1>
        <GameLogo />
        <div className="pt-4 pb-2">
            <div className="px-2">
                <Button text="Start game" color="blue" onClick={handleStartGame} />
            </div>
            <div className="flex py-2 px-2">
                <div className="pe-1 w-1/3">
                    <NumberInput
                        value={gameBoardSize.rows}
                        label="Rows"
                        name="rows"
                        onChange={handleGameBoardSizeChange}
                    />
                </div>
                <div className="px-1 w-1/3">
                    <NumberInput
                        value={gameBoardSize.columns}
                        label="Columns"
                        name="columns"
                        onChange={handleGameBoardSizeChange}
                    />
                </div>
                <div className="ps-1 w-1/3">
                    <CheckBoxInput
                        checked={infiniteGameBoard}
                        label="Infinite board"
                        name="infinite-board"
                        onChange={() => setInfiniteGameBoard((current) => !current)}
                    />
                </div>
            </div>
        </div>
    </div>;
};

export default MainMenu;

// vue/src/components/game/MainMenu.vue
<script lang="ts" setup>
import { ref } from 'vue';
import GameBoard from './GameBoard.vue';
import GameLogo from '../core/GameLogo.vue';
import Button from '../core/Button.vue';
import NumberInput from '../core/NumberInput.vue';
import CheckBoxInput from '../core/CheckBoxInput.vue';
import { GameBoardSize } from '@/types/components';

const startGame = ref<boolean>(false);
const infiniteGameBoard = ref<boolean>(false);

const getDefaultGameBoardSize = (): GameBoardSize => {
  if (window.innerWidth <= 640) {
    return { rows: 40, columns: 25 };
  }

  if (window.innerWidth <= 768) {
    return { rows: 40, columns: 50 };
  }

  return { rows: 40, columns: 70 };
};

const gameBoardSize = ref<GameBoardSize>(getDefaultGameBoardSize());

const handleStartGame = () => {
  if (gameBoardSize.value.rows > 0 && gameBoardSize.value.columns > 0) {
    startGame.value = true;
  }
};

const handleGameBoardSizeChange = (event: any) => {
  const newValue: number | string = event.target.value ? parseInt(event.target.value) : '';
  gameBoardSize.value = { ...gameBoardSize.value, [event.target.name]: newValue };
};

</script>

<template>
    <GameBoard v-if="startGame" :rows="gameBoardSize.rows" :columns="gameBoardSize.columns"
        :infiniteGameBoard="infiniteGameBoard" @back="() => startGame = false" />
    <div v-else
        class="w-full h-2/3 lg:w-1/2 rounded-md flex flex-col justify-center items-center bg-white shadow-sm border border-black">
        <h1 class="font-bold text-2xl py-3 text-blue-600">Game of Life</h1>
        <GameLogo />
        <div class="pt-4 pb-2">
            <div class="px-2">
                <Button :text="'Start game'" :color="'blue'" @click="handleStartGame" />
            </div>
            <div class="flex py-2 px-2">
                <div class="pe-1 w-1/3">
                    <NumberInput :label="'Rows'" :name="'rows'" :value="gameBoardSize.rows"
                        @change="handleGameBoardSizeChange" />
                </div>
                <div class="px-1 w-1/3">
                    <NumberInput :label="'Columns'" :name="'columns'" :value="gameBoardSize.columns"
                        @change="handleGameBoardSizeChange" />
                </div>
                <div class="ps-1 w-1/3">
                    <CheckBoxInput :label="'Infinite board'" :name="'infinite-board'" :checked="infiniteGameBoard"
                        @change="() => infiniteGameBoard = !infiniteGameBoard" />
                </div>
            </div>
        </div>
</div></template>
